### ISSUE TITLE
Notification settings not applied

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/Locative-Android#100]
All notifications are off (default?) but I get notifications anyway

Also is on `success`/ `failure` related to contactacting the locative backend or to trigger the global / related http url

**Comment by francisdb** [comment]
@kimar did you also fix this one with #109 ?

**Comment by kimar** [comment]
Fixed in fc45ea1

**Comment by francisdb** [comment]
Just confirming this is fixed. 👍
