### ISSUE TITLE
Fences not triggered any more since last updates

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/Locative-Android#107]
I'm not getting notifications / fencelogs any more. @kimar can you check if other android users have the same proble. My last log was on 25.08.2016 09:36:39

**Comment by kimar** [comment]
Could you try restarting it? Maybe the Android service went down? I can't see if it's working / not working for others unless somebody reports this.

**Comment by francisdb** [comment]
A force kill of the app indeed fixed this.
