### ISSUE TITLE
LocationService isn't working occasionally

### ISSUE THREAD

**Issue by kimar** [LocativeHQ/Locative-Android#108]
Some times the service either crashes or it's not spun up/doesn't register the Geofences correctly. The result is that no Geofences are being triggered.

We need to find out when/how this happens prior to fixing.

**Comment by francisdb** [comment]
We had a similar issue before that was related to the phone restarting #66

**Comment by kimar** [comment]
@francisdb I haven't seen this in a while, might close it. If it's related to #66 we should tackle that one and get rid of this one.

**Comment by francisdb** [comment]
I can confirm that this certainly does not happen on my phone. I had the app working reliably for months
