### ISSUE TITLE
Make notification grouping optional (opt-out)

### ISSUE THREAD

**Issue by kimar** [LocativeHQ/Locative-Android#109]

**Comment by francisdb** [comment]
Euh, make only showing last notifications optional.

**Comment by kimar** [comment]
It's opt-in now, feel free to test the latest beta.
![screenshot_20170108-185722](https://cloud.githubusercontent.com/assets/126418/21748272/f372908a-d5d4-11e6-955c-ea2c965f5cfc.png)
