### ISSUE TITLE
All parameters are 'null'

### ISSUE THREAD

**Issue by Lampy09** [LocativeHQ/Locative-Android#117]
I'm using Locative in combination with Home Assistant and it looks like the Android version of Locative sends all parameters as 'null'. Example of an intercepted request:

`<somehost>&latitude=null&longitude=null&id=null&device=null&device_type=null&device_model=null&trigger=null&timestamp=null`

**Locative version:**
2.4.0(32)

**Android version:**
6.0

**Device:**
Huawei P9 Lite

**Comment by kimar** [comment]
Hi, would you mind trying out this version of the app? It's a release from July 2016 and there might have been changes to the request format which hasn't been picked up by HA yet. If the app is crashing on startup you might need to remove the existing one first. This is due to database incompatibilities.

https://static-assets.locative.io/releases/10.apk

Please let me know if this improves anything for you.

**Comment by Banana5kin** [comment]
Downloaded and installed, will test tonight when at home. 

Thanks.

**Comment by Lampy09** [comment]
@kimar: this is what the old version (10.apk) sends:

`'/api/locative?api_password=<password>?latitude=52.297398&longitude=4.5619655&id=home&device=77dbc4b60a5c84f7&device_type=Android&device_model=HUAWEI+VNS-L31&trigger=exit&timestamp=2017-02-06+19%3A28%3A13.656'`

As you can see, the parameters are fine now (so it's definitely app version related). However this older version doesn't support extra parameters in the URL (see the multiple question marks).

**Comment by kimar** [comment]
@Lampy, mhhh that's weird as I said the new version is also sending a payload but it seems like something has changed and makes Ha not work. I'll have a look into this. I know there were issues with certain parameters that have been fixed in newer version .

Just to make sure: you are looking at real enter/exit events and not using the "send test request". Button from the settings menu, right?

**Comment by Lampy09** [comment]
Both tests (latest version and 10.apk) are done with **real** enter/exit events (GET request). I've tested against a NodeJS server to intercept what Locative is sending.

**Comment by kimar** [comment]
@Lampy09 @Banana5kin could you please try Build 11 with HA? This one should fix the custom parameter issue: https://static-assets.locative.io/releases/11.apk

**Comment by Lampy09** [comment]
Build 11 is even weirder, it **looks** like everything goes right but I can't see any requests coming in. Not in HA and not on my NodeJS server.

**Comment by kimar** [comment]
@Lampy09 @Banana5kin would you mind opting in for the beta? https://play.google.com/apps/testing/io.locative.app I've just published a release (2.4.1 (33)) that will be available within the next hours or so, this changes how request parameter encoding works, it seems the current way isn't working on all API Levels Locative is available for.

**Comment by Lampy09** [comment]
Yep that's it! It's working again! Thanks for the quick feedback.

**Comment by kimar** [comment]
@lampy09 just to double check, the beta 2.4.1(33) is working as expected? Then I'd promote it do prod so everyone gets the fix

**Comment by Lampy09** [comment]
Yes, beta 2.4.1(33) is working as expected.

**Comment by covrig** [comment]
My apologies @kimar. I was stuck without an internet connection all day. I see you solved the issue without my help. Excellent news! I told you that it was something related to the app. I also confirm that the latest beta is working properly. 
_(I was fixing the problem with a small script that was rewriting the payload sent by Locative)_

**Comment by kimar** [comment]
This has been fixed in v2.4.1 (33) b6d30d9 and will be available in the play store soon.

**Comment by kimar** [comment]
Great @covrig would you be able to tell me the fix you did? I'df just be curious as it seems like something with the parameter encoding went terribly wrong on the android side but it worked for my system. So I assumed this had to do with different Android API levels. But would be cool to know how you've mitigated this.
