### ISSUE TITLE
Publish APK at Github?

### ISSUE THREAD

**Issue by IzzySoft** [LocativeHQ/Locative-Android#120]
Would you mind attaching the `.apk` file to the corresponding `releases/` here at Github, so folks without Playstore can grab it? I could then automatically fetch it and include it with [my F-Droid compatible repo](https://android.izzysoft.de/repo).

**Comment by kimar** [comment]
@IzzySoft Locative has been discontinued, I'm closing this issue now: http://blog.locative.io/bye-everyone-df01871fe949

**Comment by IzzySoft** [comment]
A pity – but yes, that makes my request obsolete. Thanks anyway!
