### ISSUE TITLE
Fence can hardly be moved on map

### ISSUE THREAD

**Issue by kimar** [LocativeHQ/Locative-Android#19]
It's almost impossible to move the marker on a Gmap, this definitely needs some adjustment

**Comment by francisdb** [comment]
@kimar this app is currently dysfunctional, but need to find the time to fix issues.
This is related to the library you use (copied in the project) that is probably not compatible any more.

**Comment by kimar** [comment]
Yeah, now worries. I'll also try to take a look into this when I've got some time. No rush on that, it's just a side project.

**Comment by kimar** [comment]
This is still an issue and it's pretty annoying as I, on my Nexus 6P, can't move the fence at all, if I find some time I'll look into this

**Comment by francisdb** [comment]
So you moved from iphone to android?

**Comment by kimar** [comment]
Nah, I'm just sometimes using my Android Phone to better understand how things work on this platform.

**Comment by kimar** [comment]
Triaged the issue, it's been due to the `NestedScrollView` stealing the touch events thus it got cancelled and drag 'n drop didn't work correctly. I've also found a Workaround. The map is now also zoomable so the radius can be increased. This increases usability dramatically. A new version will be deployed to the Play Store soon.
