### ISSUE TITLE
Using Dagger and Otto 

### ISSUE THREAD

**Issue by chrissd23** [LocativeHQ/Locative-Android#33]
I would like to add dagger as dependency injection and otto as event bus system. 

I think we can write better code to test. I think there are various scenarios where we can write tests. Like login and logout, sign up ... and so on. 

With Otto we can reduce the use of listener. :relaxed:

What do you think @kimar @francisdb ?

**Comment by kimar** [comment]
Sure sounds good to me, I'm not familiar with those frameworks though. Only thing that we need to be cautios is to not overuse the eventbus, because from my experience this _could_ give us a hard time debugging code.

But I'm putting this into your expertise and hands 👏

**Comment by chrissd23** [comment]
I agree with you. I also have made this experience with eventbus :scream:

I will be carful :smile: , This is only an intermediate step. 

So most of all I would like to use a new architecture MVVP. Many andorid devs prefer this. 
Currently I try to understand this and how to used it for Android.

**Comment by kimar** [comment]
:cool:

**Comment by francisdb** [comment]
Go ahead. All these libs from square are great.
Do we still need butterknife with dagger? Dagger1 or 2?

**Comment by chrissd23** [comment]
Yeah :sunglasses:

I will use dagger1. I think I can show you some first steps later on this day. :blush:

**Comment by francisdb** [comment]
Looking forward to it

**Comment by kimar** [comment]
Migration to Dagger 2 is done in #115
