### ISSUE TITLE
Geofence send without moving

### ISSUE THREAD

**Issue by boced66** [LocativeHQ/Locative-Android#98]
When I leave my smartphone on a table,
Occasionally, outputs and zone entry is sent,

Before sending the log, should vérrifier if there is indeed information to send,

I propose to ask the exact location system (GPS) just before send to URL,

It happens every 30/40 minutes, the betterie should not be affected,

Thank you,
Merci,

**Comment by francisdb** [comment]
Are you seeing entries without exists?
Have you tried making the geofence larger?

In fact this is all handled by Google play Location services on Android, we could however let the user tweak the parameters:
https://developer.android.com/training/location/geofencing.html

**Comment by boced66** [comment]
I think this is the mode "doze" from Android 6.0,
I deleted Locative of battery optimization,
And it seems to work better,
Thank you for your reply, I close the ticket
