### ISSUE TITLE
Regression - notification now shows id instead of fence name

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/Locative-Android#99]
The notifications used to show the fence name, they now show a useless uuid

![screenshot_20160806-173601 2](https://cloud.githubusercontent.com/assets/161305/17457588/ad5604da-5bfc-11e6-9afb-8e6bbccd77fc.png)

**Comment by francisdb** [comment]
This fence was imported from the server

**Comment by kimar** [comment]
Thos has been fixed recently together with various ijconsistencies when impoetijg Geofences.
